/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tungb
 */
public class ChinhSuaThongTinNguoiDung extends javax.swing.JFrame {

    private Vector<String> info;
    
    /**
     * Creates new form ChinhSuaThongTinNguoiDung
     */
    public ChinhSuaThongTinNguoiDung() throws IOException, ParseException {
        initComponents();
        setInfo();
    }

    
    private void setInfo() throws IOException, ParseException {
        this.info = new Vector<>();
        info.addAll(CSDL.statement_hien_thi_thong_tin_nguoi_dung());
        this.hoDemEdit.setText(this.info.get(1));
        this.tenEdit.setText(this.info.get(2));
        Date date = new SimpleDateFormat("dd/MM/yyyy").parse(this.info.get(3));
        this.dobEdit.setDate(date);
        this.addressEdit.setText(this.info.get(4));
        this.phoneEdit.setText(this.info.get(5));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ten = new javax.swing.JLabel();
        hoDem = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        ngaySinh = new javax.swing.JLabel();
        diaChi = new javax.swing.JLabel();
        sdt = new javax.swing.JLabel();
        hoDemEdit = new javax.swing.JTextField();
        addressEdit = new javax.swing.JTextField();
        phoneEdit = new javax.swing.JTextField();
        tenEdit = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        dobEdit = new com.toedter.calendar.JDateChooser();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ten.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ten.setText("Tên");

        hoDem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hoDem.setText("Họ Đệm");

        header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("THÔNG TIN CỦA BẠN ");
        header.setToolTipText("");

        ngaySinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ngaySinh.setText("Ngày Sinh");

        diaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        diaChi.setText("Địa Chỉ");

        sdt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sdt.setText("Số Điện Thoại");

        hoDemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoDemEditActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(230, 94, 48));
        save.setText("Lưu Thông Tin");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        dobEdit.setDateFormatString("dd/MM/yyyy");

        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("Back");
        back.setMaximumSize(new java.awt.Dimension(72, 33));
        back.setMinimumSize(new java.awt.Dimension(72, 33));
        back.setPreferredSize(new java.awt.Dimension(72, 33));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hoDem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addressEdit)
                                    .addComponent(phoneEdit)
                                    .addComponent(tenEdit)
                                    .addComponent(dobEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                                    .addComponent(hoDemEdit))))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoDem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoDemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(dobEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoDemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoDemEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoDemEditActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            // TODO add your handling code here:
            String hodem = this.hoDemEdit.getText();
            String ten = this.tenEdit.getText();
            Date dob = this.dobEdit.getDate();
            String pattern = "dd/MM/yyyy";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            String date = simpleDateFormat.format(dob);
            String address = this.addressEdit.getText();
            String phone = this.phoneEdit.getText();
//            System.out.println(hodem+" "+ten+" "+dob+" "+address+" "+phone );
            CSDL.statement_sua_thong_tin_nguoi_dung(hodem, ten, date, address, phone);
        } catch (IOException ex) {
            Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            HienThiThongTinNguoiDung te = new HienThiThongTinNguoiDung();
            te.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            // TODO add your handling code here:
            HienThiThongTinNguoiDung te = new HienThiThongTinNguoiDung();
            te.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChinhSuaThongTinNguoiDung().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(ChinhSuaThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressEdit;
    private javax.swing.JButton back;
    private javax.swing.JLabel diaChi;
    private com.toedter.calendar.JDateChooser dobEdit;
    private javax.swing.JLabel header;
    private javax.swing.JLabel hoDem;
    private javax.swing.JTextField hoDemEdit;
    private javax.swing.JLabel ngaySinh;
    private javax.swing.JTextField phoneEdit;
    private javax.swing.JButton save;
    private javax.swing.JLabel sdt;
    private javax.swing.JLabel ten;
    private javax.swing.JTextField tenEdit;
    // End of variables declaration//GEN-END:variables
}
