/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

/**
 *
 * @author tanh admin dz
 */
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.util.Calendar;
import java.time.*;
import java.awt.event.*; 
import java.awt.*;  
import java.io.*;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Nhap_Thong_Tin_Hang_Ngay extends javax.swing.JFrame {
    public Nhap_Thong_Tin_Hang_Ngay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Can_nang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nhap_can_nang = new javax.swing.JTextField();
        nhap_chieu_cao = new javax.swing.JTextField();
        luu_thong_tin = new javax.swing.JButton();
        quay_lai = new javax.swing.JButton();
        hien_thi_bmi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Can_nang.setText("Cân nặng");

        jLabel1.setText("Chiều cao");

        jLabel2.setText("BMI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nhập Thông Tin Hàng Ngày");
        jLabel3.setToolTipText("");

        nhap_can_nang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhap_can_nangActionPerformed(evt);
            }
        });

        nhap_chieu_cao.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nhap_chieu_caoInputMethodTextChanged(evt);
            }
        });
        nhap_chieu_cao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhap_chieu_caoActionPerformed(evt);
            }
        });

        luu_thong_tin.setText("Lưu thông tin");
        luu_thong_tin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luu_thong_tinActionPerformed(evt);
            }
        });

        quay_lai.setText("Quay lại");
        quay_lai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quay_laiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quay_lai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Can_nang)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nhap_can_nang, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(nhap_chieu_cao)
                                    .addComponent(hien_thi_bmi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(luu_thong_tin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Can_nang)
                    .addComponent(nhap_can_nang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nhap_chieu_cao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(hien_thi_bmi, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luu_thong_tin)
                    .addComponent(quay_lai))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhap_can_nangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhap_can_nangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhap_can_nangActionPerformed
    //lay time
    private String getTime(){
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

        String formattedDate = myDateObj.format(myFormatObj);
        return formattedDate;
    }
    //lay bmi
    private String getBMI(){
        double can_nang=Double.valueOf(nhap_can_nang.getText());
        double chieu_cao=Double.valueOf(nhap_chieu_cao.getText());
        double bmi=(can_nang)/(chieu_cao * chieu_cao / 10000);
        return String.valueOf(bmi);
    }
    //lay the trang
    private String TheTrang(){
        Double bmi=Double.valueOf(this.getBMI());
        if(bmi>40) return "Béo phì độ III";
        else if(bmi>=35) return "Béo phì độ II";
        else if(bmi>=30) return "Béo phì độ I";
        else if(bmi>=25) return "Thừa cân";
        else if(bmi>=18.5) return "Bình thường";
        else if(bmi>=17) return "Gầy độ 1";
        else if(bmi>=16) return "Gầy độ 2";
        else return "Gầy độ 3";
    }
    
    //luu thong tin hang ngay
    private void luu_thong_tinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luu_thong_tinActionPerformed
        // TODO add your handling code here:
        int dk=JOptionPane.showConfirmDialog(this,"Bạn có muốn lưu thông tin","Đồng ý",JOptionPane.YES_NO_CANCEL_OPTION);
        if(dk!=JOptionPane.YES_OPTION) return;
        String s="";
        try {
            s = CSDL.ReadIDFromFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Nhap_Thong_Tin_Hang_Ngay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Nhap_Thong_Tin_Hang_Ngay.class.getName()).log(Level.SEVERE, null, ex);
        }
//        System.out.println(s);
        if(CSDL.insert_into_nhap_thong_tin_hang_ngay(s, getTime(), nhap_can_nang.getText(), nhap_chieu_cao.getText(), getBMI(), TheTrang())){
            TrangChuUser trangchu=new TrangChuUser();
            trangchu.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Mời bạn nhập lại thông tin");
        }
    }//GEN-LAST:event_luu_thong_tinActionPerformed

    private void quay_laiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quay_laiActionPerformed
        // TODO add your handling code here:
        TrangChuUser trangchu=new TrangChuUser();
            trangchu.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_quay_laiActionPerformed

    private void nhap_chieu_caoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhap_chieu_caoActionPerformed
        // TODO add your handling code here:
        try{  
        hien_thi_bmi.setText(getBMI());  
        }catch(Exception ex){System.out.println(ex);}  
    }//GEN-LAST:event_nhap_chieu_caoActionPerformed

    private void nhap_chieu_caoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nhap_chieu_caoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nhap_chieu_caoInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhap_Thong_Tin_Hang_Ngay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhap_Thong_Tin_Hang_Ngay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhap_Thong_Tin_Hang_Ngay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhap_Thong_Tin_Hang_Ngay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nhap_Thong_Tin_Hang_Ngay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Can_nang;
    private javax.swing.JLabel hien_thi_bmi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JButton luu_thong_tin;
    private javax.swing.JTextField nhap_can_nang;
    private javax.swing.JTextField nhap_chieu_cao;
    private javax.swing.JButton quay_lai;
    // End of variables declaration//GEN-END:variables
}
